apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
      # Permite buscar traces por traceId diretamente do Grafana Explore.
      serviceMap:
        datasourceUid: prometheus
    editable: true

  - name: AiChatFlow SQLite
    uid: sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      path: /data/aichatflow.db
    editable: true
