BEGIN;

ALTER TABLE model_aliases
  ADD COLUMN IF NOT EXISTS failure_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_failure_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS last_rollback_at TIMESTAMP;

COMMIT;
